#!/usr/bin/python

# script to poll the RPi rain sensor
import RPi.GPIO as g
import Pyro4
from collections import defaultdict

class RainSensor(object):
	# running setmode on each call is not a good idea, fix when working...
	def __init__(self):
		self.rs=defaultdict(list)

	def poll_rain_sensor(self):
		g.setmode(g.BCM)
		gpio_nums=[2,3,4,17,27,22,10,9,11,5,6,13,19,26,20,21]
		for i in gpio_nums:
			g.setup(i,g.IN)
		for i in range(0,len(gpio_nums)):
			self.rs[(i+1)]=g.input(gpio_nums[i])
		return self.rs

def main():
	daemon = Pyro4.Daemon('10.2.5.107')
	ns=Pyro4.locateNS()
	uri = daemon.register(RainSensor())
	ns.register("rainSensor",uri)

	print "Ready."
	daemon.requestLoop()


if __name__=="main":
	main()
# start name server
# python -m Pyro4.naming -n 10.2.5.107	